import type { ProviderId } from '../providers/types';
import type { ProviderLinkId } from '../links/ProviderLinkRegistry';
import { getProviderLink } from '../links/ProviderLinkRegistry';
import { DASHBOARD_ACTION_IDS, type DashboardActionId } from './DashboardActionProtocol';

export type DashboardActionKind =
  'refresh' | 'mutation' | 'diagnostic' | 'navigation' | 'clipboard' | 'export';

export interface DashboardActionDefinition {
  id: DashboardActionId;
  providerId?: ProviderId;
  /** Present for navigation actions so the host-side command remains tied to one registry link. */
  providerLinkId?: ProviderLinkId;
  commandId: string;
  kind: DashboardActionKind;
  mutexGroup?: string;
  retryable: boolean;
  successMessage: string;
  workingMessage: string;
}

const definitions: readonly DashboardActionDefinition[] = [
  {
    id: 'refresh-all',
    commandId: 'aiLimitLedger.refresh',
    kind: 'refresh',
    mutexGroup: 'refresh:all',
    retryable: true,
    successMessage: 'Updated',
    workingMessage: 'Refreshing…',
  },
  {
    id: 'refresh-codex',
    providerId: 'codex',
    commandId: 'aiLimitLedger.refreshCodex',
    kind: 'refresh',
    mutexGroup: 'provider:codex',
    retryable: true,
    successMessage: 'Updated',
    workingMessage: 'Refreshing Codex',
  },
  {
    id: 'refresh-claude',
    providerId: 'claude',
    commandId: 'aiLimitLedger.refreshClaude',
    kind: 'refresh',
    mutexGroup: 'provider:claude',
    retryable: true,
    successMessage: 'Updated',
    workingMessage: 'Refreshing Claude',
  },
  {
    id: 'open-provider-settings',
    commandId: 'aiLimitLedger.openSettings',
    kind: 'navigation',
    retryable: false,
    successMessage: 'Opened',
    workingMessage: 'Opening…',
  },
  {
    id: 'show-logs',
    commandId: 'aiLimitLedger.showLogs',
    kind: 'navigation',
    retryable: false,
    successMessage: 'Opened',
    workingMessage: 'Opening…',
  },
  {
    id: 'copy-redacted-diagnostics',
    commandId: 'aiLimitLedger.copyRedactedDiagnostics',
    kind: 'clipboard',
    retryable: true,
    successMessage: 'Copied',
    workingMessage: 'Copying…',
  },
  {
    id: 'export-redacted-support-bundle',
    commandId: 'aiLimitLedger.exportRedactedSupportBundle',
    kind: 'export',
    retryable: true,
    successMessage: 'Exported',
    workingMessage: 'Exporting…',
  },
  {
    id: 'restart-codex-app-server',
    providerId: 'codex',
    commandId: 'aiLimitLedger.restartAppServer',
    kind: 'mutation',
    mutexGroup: 'provider:codex',
    retryable: true,
    successMessage: 'Restarted',
    workingMessage: 'Restarting…',
  },
  {
    id: 'diagnose-codex',
    providerId: 'codex',
    commandId: 'aiLimitLedger.diagnoseCodexIntegration',
    kind: 'diagnostic',
    mutexGroup: 'provider:codex',
    retryable: true,
    successMessage: 'Checked',
    workingMessage: 'Checking…',
  },
  {
    id: 'open-codex-usage',
    providerId: 'codex',
    providerLinkId: 'codex-usage',
    commandId: 'aiLimitLedger.openCodexUsagePage',
    kind: 'navigation',
    retryable: true,
    successMessage: 'Opened',
    workingMessage: 'Opening…',
  },
  {
    id: 'enable-claude',
    providerId: 'claude',
    commandId: 'aiLimitLedger.enableClaudeCode',
    kind: 'mutation',
    mutexGroup: 'provider:claude',
    retryable: false,
    successMessage: 'Enabled',
    workingMessage: 'Enabling…',
  },
  {
    id: 'disable-claude',
    providerId: 'claude',
    commandId: 'aiLimitLedger.disableClaudeCode',
    kind: 'mutation',
    mutexGroup: 'provider:claude',
    retryable: false,
    successMessage: 'Disabled',
    workingMessage: 'Disabling…',
  },
  {
    id: 'repair-claude',
    providerId: 'claude',
    commandId: 'aiLimitLedger.repairClaudeCodeIntegration',
    kind: 'mutation',
    mutexGroup: 'provider:claude',
    retryable: false,
    successMessage: 'Repaired',
    workingMessage: 'Repairing…',
  },
  {
    id: 'recheck-claude',
    providerId: 'claude',
    commandId: 'aiLimitLedger.recheckClaudeIntegrationHealth',
    kind: 'diagnostic',
    mutexGroup: 'provider:claude',
    retryable: true,
    successMessage: 'Checked',
    workingMessage: 'Checking…',
  },
  {
    id: 'diagnose-claude',
    providerId: 'claude',
    commandId: 'aiLimitLedger.diagnoseClaudeCodeIntegration',
    kind: 'diagnostic',
    mutexGroup: 'provider:claude',
    retryable: true,
    successMessage: 'Checked',
    workingMessage: 'Checking…',
  },
  {
    id: 'open-claude-usage',
    providerId: 'claude',
    providerLinkId: 'claude-usage',
    commandId: 'aiLimitLedger.openClaudeUsagePage',
    kind: 'navigation',
    retryable: true,
    successMessage: 'Opened',
    workingMessage: 'Opening…',
  },
  {
    id: 'open-claude-install-guide',
    providerId: 'claude',
    providerLinkId: 'claude-install',
    commandId: 'aiLimitLedger.openClaudeInstallGuide',
    kind: 'navigation',
    retryable: true,
    successMessage: 'Opened',
    workingMessage: 'Opening…',
  },
  {
    id: 'launch-claude-terminal',
    providerId: 'claude',
    commandId: 'aiLimitLedger.launchClaudeInTerminal',
    kind: 'navigation',
    retryable: false,
    successMessage: 'Opened',
    workingMessage: 'Opening…',
  },
  {
    id: 'copy-claude-diagnostics',
    providerId: 'claude',
    commandId: 'aiLimitLedger.copyClaudeDiagnostics',
    kind: 'clipboard',
    retryable: true,
    successMessage: 'Copied',
    workingMessage: 'Copying…',
  },
  {
    id: 'open-claude-code',
    providerId: 'claude',
    commandId: 'aiLimitLedger.openClaudeCode',
    kind: 'navigation',
    retryable: true,
    successMessage: 'Opened',
    workingMessage: 'Opening…',
  },
  {
    id: 'copy-claude-usage',
    providerId: 'claude',
    commandId: 'aiLimitLedger.copyClaudeUsageCommand',
    kind: 'clipboard',
    retryable: true,
    successMessage: 'Copied',
    workingMessage: 'Copying…',
  },
  {
    id: 'open-claude-enhanced-mode-docs',
    providerId: 'claude',
    providerLinkId: 'claude-vscode-docs',
    commandId: 'aiLimitLedger.openCliEnhancedModeDocs',
    kind: 'navigation',
    retryable: true,
    successMessage: 'Opened',
    workingMessage: 'Opening…',
  },
  {
    id: 'enable-claude-auto-repair',
    providerId: 'claude',
    commandId: 'aiLimitLedger.enableClaudeAutomaticRepair',
    kind: 'mutation',
    mutexGroup: 'provider:claude',
    retryable: false,
    successMessage: 'Enabled',
    workingMessage: 'Enabling…',
  },
  {
    id: 'disable-claude-auto-repair',
    providerId: 'claude',
    commandId: 'aiLimitLedger.disableClaudeAutomaticRepair',
    kind: 'mutation',
    mutexGroup: 'provider:claude',
    retryable: false,
    successMessage: 'Disabled',
    workingMessage: 'Disabling…',
  },
  {
    id: 'enable-claude-oauth',
    providerId: 'claude',
    commandId: 'aiLimitLedger.enableClaudeOAuthUsage',
    kind: 'mutation',
    mutexGroup: 'provider:claude',
    retryable: false,
    successMessage: 'Enabled',
    workingMessage: 'Enabling…',
  },
  {
    id: 'disable-claude-oauth',
    providerId: 'claude',
    commandId: 'aiLimitLedger.disableClaudeOAuthUsage',
    kind: 'mutation',
    mutexGroup: 'provider:claude',
    retryable: false,
    successMessage: 'Disabled',
    workingMessage: 'Disabling…',
  },
  {
    id: 'open-claude-oauth-docs',
    providerId: 'claude',
    commandId: 'aiLimitLedger.openExperimentalClaudeUsageDocs',
    kind: 'navigation',
    retryable: true,
    successMessage: 'Opened',
    workingMessage: 'Opening…',
  },
  {
    id: 'connect-copilot',
    providerId: 'copilot',
    commandId: 'aiLimitLedger.connectCopilotUsage',
    kind: 'mutation',
    mutexGroup: 'provider:copilot',
    retryable: false,
    successMessage: 'Connected',
    workingMessage: 'Connecting…',
  },
  {
    id: 'disconnect-copilot',
    providerId: 'copilot',
    commandId: 'aiLimitLedger.disconnectCopilotUsage',
    kind: 'mutation',
    mutexGroup: 'provider:copilot',
    retryable: false,
    successMessage: 'Disconnected',
    workingMessage: 'Disconnecting…',
  },
  {
    id: 'refresh-copilot',
    providerId: 'copilot',
    commandId: 'aiLimitLedger.refreshCopilotUsage',
    kind: 'refresh',
    mutexGroup: 'provider:copilot',
    retryable: true,
    successMessage: 'Updated',
    workingMessage: 'Refreshing…',
  },
  {
    id: 'configure-copilot-plan',
    providerId: 'copilot',
    commandId: 'aiLimitLedger.configureCopilotPlan',
    kind: 'mutation',
    mutexGroup: 'provider:copilot',
    retryable: false,
    successMessage: 'Saved',
    workingMessage: 'Saving…',
  },
  {
    id: 'diagnose-copilot',
    providerId: 'copilot',
    commandId: 'aiLimitLedger.diagnoseCopilotIntegration',
    kind: 'diagnostic',
    mutexGroup: 'provider:copilot',
    retryable: true,
    successMessage: 'Checked',
    workingMessage: 'Checking…',
  },
  {
    id: 'open-copilot-usage',
    providerId: 'copilot',
    providerLinkId: 'copilot-billing',
    commandId: 'aiLimitLedger.openCopilotUsage',
    kind: 'navigation',
    retryable: true,
    successMessage: 'Opened',
    workingMessage: 'Opening…',
  },
  {
    id: 'enable-copilot-experimental',
    providerId: 'copilot',
    commandId: 'aiLimitLedger.enableExperimentalCopilotUsage',
    kind: 'mutation',
    mutexGroup: 'provider:copilot',
    retryable: false,
    successMessage: 'Enabled',
    workingMessage: 'Enabling…',
  },
  {
    id: 'disable-copilot-experimental',
    providerId: 'copilot',
    commandId: 'aiLimitLedger.disableExperimentalCopilotUsage',
    kind: 'mutation',
    mutexGroup: 'provider:copilot',
    retryable: false,
    successMessage: 'Disabled',
    workingMessage: 'Disabling…',
  },
  {
    id: 'enable-grok',
    providerId: 'grok',
    commandId: 'aiLimitLedger.enableGrokUsage',
    kind: 'mutation',
    mutexGroup: 'provider:grok',
    retryable: false,
    successMessage: 'Enabled',
    workingMessage: 'Enabling…',
  },
  {
    id: 'disable-grok',
    providerId: 'grok',
    commandId: 'aiLimitLedger.disableGrokUsage',
    kind: 'mutation',
    mutexGroup: 'provider:grok',
    retryable: false,
    successMessage: 'Disabled',
    workingMessage: 'Disabling…',
  },
  {
    id: 'refresh-grok',
    providerId: 'grok',
    commandId: 'aiLimitLedger.refreshGrokUsage',
    kind: 'refresh',
    mutexGroup: 'provider:grok',
    retryable: true,
    successMessage: 'Updated',
    workingMessage: 'Refreshing…',
  },
  {
    id: 'recheck-grok',
    providerId: 'grok',
    commandId: 'aiLimitLedger.recheckGrokInstallation',
    kind: 'diagnostic',
    mutexGroup: 'provider:grok',
    retryable: true,
    successMessage: 'Checked',
    workingMessage: 'Checking…',
  },
  {
    id: 'launch-grok-login',
    providerId: 'grok',
    commandId: 'aiLimitLedger.launchGrokLogin',
    kind: 'navigation',
    mutexGroup: 'provider:grok',
    retryable: false,
    successMessage: 'Opened',
    workingMessage: 'Opening…',
  },
  {
    id: 'diagnose-grok',
    providerId: 'grok',
    commandId: 'aiLimitLedger.diagnoseGrokIntegration',
    kind: 'diagnostic',
    mutexGroup: 'provider:grok',
    retryable: true,
    successMessage: 'Checked',
    workingMessage: 'Checking…',
  },
  {
    id: 'open-grok-install-guide',
    providerId: 'grok',
    providerLinkId: 'grok-install',
    commandId: 'aiLimitLedger.openGrokInstallGuide',
    kind: 'navigation',
    retryable: true,
    successMessage: 'Opened',
    workingMessage: 'Opening…',
  },
  {
    id: 'open-grok-usage',
    providerId: 'grok',
    providerLinkId: 'grok-billing',
    commandId: 'aiLimitLedger.openGrokUsage',
    kind: 'navigation',
    retryable: true,
    successMessage: 'Opened',
    workingMessage: 'Opening…',
  },
  {
    id: 'copy-grok-usage',
    providerId: 'grok',
    commandId: 'aiLimitLedger.copyClaudeUsageCommand',
    kind: 'clipboard',
    retryable: true,
    successMessage: 'Copied',
    workingMessage: 'Copying…',
  },
  {
    id: 'enable-grok-experimental',
    providerId: 'grok',
    commandId: 'aiLimitLedger.enableExperimentalGrokUsage',
    kind: 'mutation',
    mutexGroup: 'provider:grok',
    retryable: false,
    successMessage: 'Enabled',
    workingMessage: 'Enabling…',
  },
  {
    id: 'disable-grok-experimental',
    providerId: 'grok',
    commandId: 'aiLimitLedger.disableExperimentalGrokUsage',
    kind: 'mutation',
    mutexGroup: 'provider:grok',
    retryable: false,
    successMessage: 'Disabled',
    workingMessage: 'Disabling…',
  },
];

const byId = new Map(definitions.map((definition) => [definition.id, definition]));

if (byId.size !== DASHBOARD_ACTION_IDS.length) {
  throw new Error('Dashboard action registry contains duplicate or missing action IDs.');
}

for (const definition of definitions) {
  if (definition.providerLinkId) {
    const link = getProviderLink(definition.providerLinkId);
    if (definition.providerId !== link.providerId)
      throw new Error(`Dashboard action ${definition.id} is mapped to the wrong provider link.`);
  }
}

export const DASHBOARD_ACTION_REGISTRY: readonly DashboardActionDefinition[] = definitions;

export function getDashboardActionDefinition(
  actionId: DashboardActionId,
): DashboardActionDefinition | undefined {
  return byId.get(actionId);
}

export function isRegisteredDashboardAction(actionId: string): actionId is DashboardActionId {
  return DASHBOARD_ACTION_IDS.includes(actionId as DashboardActionId);
}
